# Generated by Django 3.1.2 on 2020-11-07 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_program_bidang'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='tutor_name',
        ),
    ]
