# Generated by Django 3.1.2 on 2020-11-16 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_remove_program_tutor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='special_program',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lengkap', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('SISWA', 'Siswa'), ('GURU', 'Guru')], default='siswa', max_length=5)),
                ('nomor_whatsapp', models.CharField(max_length=100)),
                ('sekolah', models.CharField(max_length=100)),
                ('kota', models.CharField(max_length=100)),
                ('provinsi', models.CharField(max_length=100)),
                ('bidang', models.CharField(choices=[('matematika', 'Matematika SMA'), ('fisika', 'Fisika SMA'), ('kimia', 'Kimia SMA'), ('biologi', 'Biologi SMA'), ('komputer', 'Komputer SMA'), ('ekonomi', 'Ekonomi SMA'), ('astronomi', 'Astronomi SMA'), ('geografi', 'Geografi SMA'), ('kebumian', 'Kebumian SMA'), ('matematika-smp', 'Matematika SMP'), ('ipa-smp', 'IPA SMP'), ('ips-smp', 'IPS SMP')], default='matematika', max_length=20)),
                ('guru_pembimbing', models.CharField(max_length=100)),
                ('nomor_guru_pembimbing', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
