# Generated by Django 3.1.2 on 2020-11-18 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201116_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('SISWA', 'Siswa'), ('GURU', 'Guru')], default='SISWA', max_length=5),
        ),
    ]
